name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # Déclenche le workflow uniquement sur main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # ton username Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # token personnel Docker Hub

      # Étape 3 : build et push de l'image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: itdream23/mon_image_tp:latest
